name: simple_barrel_generator
description: A simple barrel file generator for Dart/Flutter projects.
version: 0.0.1
homepage: https://github.com/r-koubou/dart_simple_barrel_generator
repository: https://github.com/r-koubou/dart_simple_barrel_generator

platforms:
  windows:
  macos:
  linux:

executables:
  simple_barrel_generator:

topics:
  - codegen
  - barrel

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  glob: ^2.1.3


dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
